### PR TITLE
Extra Space Removed From Output File

### PR DESCRIPTION
**Pull request by ConnectNitish**
Because of Recusrion invocation , White space was printed twice. Hence we don't white space when data type is of list.

### CODE REVIEW

**Comment by masterashu** [comment]
@ConnectNitish If you're making this pull request for to be counted in hacktoberfest, it will not be counted. Since the pull request is not opened in October. Make another pull pull request in the month of October to be counted in  hacktoberfest.

**Comment by ConnectNitish** [comment]
Ok sure.

**Comment by ConnectNitish** [comment]
Hi Please assign this task to me.

**Comment by masterashu** [comment]
Okk sure. Still remember, for a PR to be eligible in hacktoberfest it is not necessary it should be merged to be counted. You can still see the rules here. https://hacktoberfest.digitalocean.com/details#participation-rules

**Pull request closed without merging**
